version: '3.2'
services:
  api:
    build: api
    ports:
      - 3000:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql:mysql
  backend:
    build: backend
    ports:
      - 2000:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=esapp
      - MYSQL_USER=esapp
      - MYSQL_PASSWORD=secret
    restart: always
    volumes:
      - ./mysql-data/data:/var/lib/mysql
      - ./mysql-data/import:/docker-entrypoint-initdb.d